services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8443:8443
      - 9080:9080
      - 9443:9443
    networks:
      - dockerhost
      - http-int
    volumes:
      - /data/docker/volumes/nginx/conf/:/etc/nginx/conf.d
      - /data/docker/volumes/nginx/site:/usr/share/nginx/html
      - /data/docker/volumes/nginx/letsencrypt/etc:/etc/letsencrypt
      - /data/docker/volumes/nginx/certbot/www:/var/www/certbot
    environment:
      - TZ=Europe/Berlin
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    restart: unless-stopped
    volumes:
      - /data/docker/volumes/nginx/letsencrypt/etc:/etc/letsencrypt
      - /data/docker/volumes/nginx/letsencrypt/log:/var/log/letsencrypt
      - /data/docker/volumes/nginx/certbot/www:/var/www/certbot
    environment:
      - TZ=Europe/Berlin
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  dockerhome:
    image: pkdevel/docker-home:latest
    container_name: dockerhome
    restart: unless-stopped
    ports:
      - 6969:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  http-int:
