services:
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - 8086:8086
    volumes:
      - /data/docker/volumes/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - /data/docker/volumes/influxdb/data:/var/lib/influxdb
    environment:
      TZ: Europe/Berlin

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - influxdb
    networks:
      - monitoring
      - web
    volumes:
      - /data/docker/volumes/grafana/data:/var/lib/grafana
      - /data/docker/volumes/grafana/grafana.ini:/etc/grafana/grafana.ini:rw
    environment:
      TZ: Europe/Berlin
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)"
      - "traefik.http.routers.grafana.middlewares=redirect-to-https"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    networks:
      - monitoring
      - web
    volumes:
      - /data/docker/volumes/beszel/data:/beszel_data
      - /data/docker/volumes/beszel/socket:/beszel_socket
    environment:
      TZ: Europe/Berlin
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.beszel.rule=Host(`beszel.${DOMAIN}`)"
      - "traefik.http.routers.beszel.middlewares=redirect-to-https"
      - "traefik.http.services.beszel.loadbalancer.server.port=8090"

  beszel-agent:
    image: henrygd/beszel-agent:latest
    hostname: ${HOSTNAME}
    container_name: beszel-agent
    restart: unless-stopped
    networks:
      - monitoring
    volumes:
      - /data/docker/volumes/beszel/agent_data:/var/lib/beszel-agent
      - /data/docker/volumes/beszel/socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/usb/wd/.beszel:/extra-filesystems/wd:ro
    environment:
      TZ: Europe/Berlin
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: http://beszel:8090
      TOKEN: ${BESZEL_TOKEN}
      KEY: ${BESZEL_KEY}

networks:
  monitoring:
