services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    networks:
      - web-ext
      - dockerhost
    volumes:
      - /data/docker/volumes/nginx/conf/:/etc/nginx/conf.d
    environment:
      - TZ=Europe/Berlin
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web-ext"
      - "traefik.http.routers.nginx.entrypoints=websecure-ext"
      - "traefik.http.routers.nginx.rule=Host(`home.${DOMAIN}`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - "--global.checkNewVersion=false"
      - "--global.sendAnonymousUsage=false"

      - "--log.level=INFO"
      - "--accessLog.filePath=/log/access.log"

      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.asDefault=true"
      - "--entrypoints.web.observability.accessLogs=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.asDefault=true"
      - "--entrypoints.websecure.observability.accessLogs=false"
      - "--entrypoints.websecure-ext.address=:9443"

      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      # - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt.acme.email=${T_MAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.websecure.http.tls.certresolver=letsencrypt"
      - "--entrypoints.websecure-ext.http.tls.certresolver=letsencrypt"
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp
      - 9443:9443/tcp
      - 9443:9443/udp
    networks:
      - web
      - web-ext
      - dockerhost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/docker/volumes/traefik/letsencrypt:/letsencrypt
      - /data/docker/volumes/traefik/log:/log
    environment:
      - TZ=Europe/Berlin
      - CF_DNS_API_TOKEN=${CF_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.middlewares=redirect-to-https"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

  dockerhome:
    image: pkdevel/docker-home:latest
    container_name: dockerhome
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.dockerhome.rule=Host(`docker.${DOMAIN}`)"
      - "traefik.http.routers.dockerhome.middlewares=redirect-to-https"
      - "traefik.http.services.dockerhome.loadbalancer.server.port=8080"

  glance:
    image: glanceapp/glance
    container_name: glance
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /data/docker/volumes/glance:/app/config
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.glance.rule=Host(`glance.${DOMAIN}`)"
      - "traefik.http.routers.glance.middlewares=redirect-to-https"
      - "traefik.http.services.glance.loadbalancer.server.port=8080"

networks:
  web:
    name: web
  web-ext:
    name: web-ext
