services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    networks:
      - web
    environment:
      - PUID=1337
      - PGID=1337
      - TZ=Europe/Berlin
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /data/docker/volumes/jellyfin:/config
      - /data/jellyfin-cache:/config/cache
      - /share/media/tv:/data/tvshows
      - /share/media/movies:/data/movies
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)"
      - "traefik.http.routers.jellyfin.middlewares=redirect-to-https"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    networks:
      - web
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Berlin
    volumes:
      - /data/docker/volumes/jellyseerr:/app/config
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.${DOMAIN}`)"
      - "traefik.http.routers.jellyseerr.middlewares=redirect-to-https"
      - "traefik.http.services.jellyseerr.loadbalancer.server.port=5055"
