services:
  nzbget:
    image: nzbgetcom/nzbget:latest
    container_name: nzbget
    restart: unless-stopped
    networks:
      - nzbget
      - web
    volumes:
      - /data/docker/volumes/nzbget:/config
      - /share/downloads:/share/downloads
      - /share/media:/share/media
    environment:
      - PUID=1337
      - PGID=1337
      - TZ=Europe/Berlin
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.nzbget.rule=Host(`nzbget.${DOMAIN}`)"
      - "traefik.http.routers.nzbget.middlewares=redirect-to-https"
      - "traefik.http.services.nzbget.loadbalancer.server.port=6789"

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    networks:
      - radarr
      - nzbget
      - web
    volumes:
      - /data/docker/volumes/radarr:/config
      - /share/media:/share/media
    environment:
      - PUID=1337
      - PGID=1337
      - TZ=Europe/Berlin
      - UMASK_SET=002
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN}`)"
      - "traefik.http.routers.radarr.middlewares=redirect-to-https"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"

  radarr-tbot:
    image: itsmegb/telegram-radarr-bot:latest
    container_name: radarr-tbot
    restart: unless-stopped
    depends_on:
      - radarr
    networks:
      - radarr
    volumes:
      - /data/docker/volumes/radarr-telegram-bot:/config
    environment:
      - TZ=Europe/Berlin

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    networks:
      - sonarr
      - nzbget
      - web
    volumes:
      - /data/docker/volumes/sonarr:/config
      - /share/media:/share/media
    environment:
      - PUID=1337
      - PGID=1337
      - TZ=Europe/Berlin
      - UMASK_SET=002
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)"
      - "traefik.http.routers.sonarr.middlewares=redirect-to-https"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"

  sonarr-tbot:
    image: subzero79/docker-telegram-sonarr-bot:latest
    container_name: sonarr-tbot
    restart: unless-stopped
    depends_on:
      - sonarr
    networks:
      - sonarr
    volumes:
      - /data/docker/volumes/sonarr-telegram-bot:/config
    environment:
      - TZ=Europe/Berlin

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr
    networks:
      - radarr
      - sonarr
      - nzbget
      - web
    volumes:
      - /data/docker/volumes/prowlarr:/config
    environment:
      - PUID=1337
      - PGID=1337
      - TZ=Europe/Berlin
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAIN}`)"
      - "traefik.http.routers.prowlarr.middlewares=redirect-to-https"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr
    user: 1337:1337
    networks:
      - radarr
      - sonarr
    volumes:
      - /data/docker/volumes/recyclarr:/config
    environment:
      - TZ=Europe/Berlin

networks:
  nzbget:
  radarr:
  sonarr:
