services:
  atuin:
    image: ghcr.io/atuinsh/atuin:latest
    container_name: atuin
    restart: unless-stopped
    ports:
      - 8888:8888
    networks:
      - atuin
    environment:
      ATUIN_HOST: 0.0.0.0
      ATUIN_OPEN_REGISTRATION: false
      ATUIN_DB_URI: postgres://$ATUIN_DB_USERNAME:$ATUIN_DB_PASSWORD@atuin-db/$ATUIN_DB_NAME
      RUST_LOG: info,atuin_server=debug
    volumes:
      - /data/docker/volumes/atuin:/config
    command: server start

  atuin-db:
    image: postgres:14
    container_name: atuin-db
    restart: unless-stopped
    networks:
      - atuin
    environment:
      POSTGRES_USER: ${ATUIN_DB_USERNAME}
      POSTGRES_PASSWORD: ${ATUIN_DB_PASSWORD}
      POSTGRES_DB: ${ATUIN_DB_NAME}
    volumes:
      - /data/docker/volumes/atuin-db:/var/lib/postgresql/data

networks:
  atuin:
