services:
  restic-backup:
    image: mazzolino/restic
    hostname: docker
    container_name: restic-backup
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      RUN_ON_STARTUP: "true"
      BACKUP_CRON: "0 30 3 * * *"
      RESTIC_REPOSITORY: /mnt/backup
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      RESTIC_BACKUP_SOURCES: /mnt/volumes
      RESTIC_BACKUP_ARGS: >-
        --tag docker-volumes
        --exclude *.tmp
        --verbose
      RESTIC_FORGET_ARGS: >-
        --keep-last 10
        --keep-daily 7
        --keep-weekly 5
        --keep-monthly 12
    volumes:
      - /data/docker/volumes:/mnt/volumes
      - /share/backup/docker-volumes:/mnt/backup

  restic-prune:
    image: mazzolino/restic
    hostname: docker
    container_name: restic-prune
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      SKIP_INIT: "true"
      RUN_ON_STARTUP: "true"
      PRUNE_CRON: "0 0 4 * * *"
      RESTIC_REPOSITORY: /mnt/backup
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
    volumes:
      - /share/backup/docker-volumes:/mnt/backup

  restic-check:
    image: mazzolino/restic
    hostname: docker
    container_name: restic-check
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      SKIP_INIT: "true"
      RUN_ON_STARTUP: "false"
      CHECK_CRON: "0 15 5 * * *"
      RESTIC_CHECK_ARGS: >-
        --read-data-subset=10%
      RESTIC_REPOSITORY: /mnt/backup
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
    volumes:
      - /share/backup/docker-volumes:/mnt/backup
